CREATE TABLE IF NOT EXISTS public.livreur_api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER,
  livreur_id UUID,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL,
  message TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.livreur_api_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_livreur_api_logs_order_id ON public.livreur_api_logs(order_id);
CREATE INDEX IF NOT EXISTS idx_livreur_api_logs_livreur_id ON public.livreur_api_logs(livreur_id);
CREATE INDEX IF NOT EXISTS idx_livreur_api_logs_created_at ON public.livreur_api_logs(created_at DESC);

DROP POLICY IF EXISTS "Administrators view driver api logs" ON public.livreur_api_logs;
DROP POLICY IF EXISTS "Administrators manage driver api logs" ON public.livreur_api_logs;

CREATE POLICY "Administrators view driver api logs"
ON public.livreur_api_logs
FOR SELECT
TO authenticated
USING (public.has_role(auth.uid(), 'administrateur'::app_role));

CREATE POLICY "Administrators manage driver api logs"
ON public.livreur_api_logs
FOR ALL
TO authenticated
USING (public.has_role(auth.uid(), 'administrateur'::app_role))
WITH CHECK (public.has_role(auth.uid(), 'administrateur'::app_role));